"""16x16 pixel-art technology marks, drawn to read at 3px-per-cell.
Each entry: (rows, palette). '.' is transparent."""

def _i(rows, **pal):
    return (rows, pal)

ICONS = {}

ICONS["C++"] = _i([
    "................",
    "..BBBBBBBBBBBB..",
    ".BBBBBBBBBBBBBB.",
    ".BB..WWWW....BB.",
    ".BB.WW..WW...BB.",
    ".BBWW........BB.",
    ".BBWW.....W..BB.",
    ".BBWW....WWW.BB.",
    ".BBWW.....W..BB.",
    ".BBWW........BB.",
    ".BB.WW..WW...BB.",
    ".BB..WWWW....BB.",
    ".BBBBBBBBBBBBBB.",
    "..BBBBBBBBBBBB..",
    "................",
    "................",
], B="#00599C", W="#FFFFFF")

ICONS["PYTHON"] = _i([
    ".....BBBBBB.....",
    "....BB....BB....",
    "....BB.WW.BB....",
    "....BB....BB....",
    "....BB....BB....",
    "..BBBBBBBBBB....",
    "..BBBBBBBBBBBB..",
    "..BBB......YYY..",
    "..BBB......YYY..",
    "..YYYYYYYYYYYY..",
    "....YYYYYYYYYY..",
    "....YY....YY....",
    "....YY....YY....",
    "....YY.WW.YY....",
    "....YY....YY....",
    ".....YYYYYY.....",
], B="#4B8BBE", Y="#FFD43B", W="#FFFFFF")

ICONS["JAVA"] = _i([
    ".....R...R......",
    "....R...R..R....",
    "....R..R...R....",
    ".....R...R......",
    "....R...R..R....",
    "................",
    ".WWWWWWWWWW.....",
    ".WWWWWWWWWW.WW..",
    ".WWWWWWWWWW..WW.",
    ".WWWWWWWWWW.WW..",
    "..WWWWWWWW......",
    "...WWWWWW.......",
    "................",
    ".RRRRRRRRRRRR...",
    "..RRRRRRRRRR....",
    "................",
], R="#F89820", W="#FFFFFF")

ICONS["JAVASCRIPT"] = _i([
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
    "YYYYY..KKYY.KKKY",
    "YYYYYY..KYYK...Y",
    "YYYYYY..KYYK...Y",
    "YYYYYY..KYY.KK.Y",
    "YYYYK...KYYYYY.Y",
    "YYYYK...KYYK...Y",
    "YYYYY.KK.YY.KK.Y",
    "YYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYY",
], Y="#F7DF1E", K="#0A0A12")

ICONS["SQL"] = _i([
    "................",
    "................",
    "...CCCCCCCCCC...",
    "..C..........C..",
    "...CCCCCCCCCC...",
    "..C..........C..",
    "..C..........C..",
    "...CCCCCCCCCC...",
    "..C..........C..",
    "..C..........C..",
    "...CCCCCCCCCC...",
    "..C..........C..",
    "...CCCCCCCCCC...",
    "................",
    "................",
    "................",
], C="#5CE1E6")

_ATOM = [
    "................",
    "......CCCC......",
    "....CC....CC....",
    "...C........C...",
    "..C..CCCCCC..C..",
    ".C..C......C..C.",
    ".C.C...CC...C.C.",
    ".C.C..CCCC..C.C.",
    ".C.C...CC...C.C.",
    ".C..C......C..C.",
    "..C..CCCCCC..C..",
    "...C........C...",
    "....CC....CC....",
    "......CCCC......",
    "................",
    "................",
]
ICONS["REACT"] = _i(_ATOM, C="#61DAFB")
ICONS["REACT NATIVE"] = _i(_ATOM, C="#A9B7FF")

ICONS["NODE.JS"] = _i([
    "......GGGG......",
    ".....G....G.....",
    "....G......G....",
    "...G........G...",
    "..G..........G..",
    ".G............G.",
    "G..............G",
    "G..............G",
    "G..............G",
    ".G............G.",
    "..G..........G..",
    "...G........G...",
    "....G......G....",
    ".....G....G.....",
    "......GGGG......",
    "................",
], G="#68A063")

ICONS["EXPRESS"] = _i([
    "................",
    "................",
    "................",
    "..WWWW....WWWW..",
    "...WWWW..WWWW...",
    "....WWWWWWWW....",
    ".....WWWWWW.....",
    "......WWWW......",
    ".....WWWWWW.....",
    "....WWWWWWWW....",
    "...WWWW..WWWW...",
    "..WWWW....WWWW..",
    "................",
    "..WWWWWWWWWWWW..",
    "................",
    "................",
], W="#E8E8F0")

ICONS["FASTAPI"] = _i([
    "................",
    "....TTTTTTTT....",
    "..TTTTTTTTTTTT..",
    ".TTTTTTTWTTTTTT.",
    ".TTTTTTWWTTTTTT.",
    "TTTTTTWWWTTTTTTT",
    "TTTTTWWWWWWTTTTT",
    "TTTTTTTWWWWTTTTT",
    "TTTTTTTTWWWTTTTT",
    "TTTTTTTWWTTTTTTT",
    "TTTTTTWWTTTTTTTT",
    ".TTTTTWTTTTTTTT.",
    ".TTTTTTTTTTTTTT.",
    "..TTTTTTTTTTTT..",
    "....TTTTTTTT....",
    "................",
], T="#05998B", W="#FFFFFF")

ICONS["FLASK"] = _i([
    "................",
    ".....WWWWWW.....",
    ".......WW.......",
    ".......WW.......",
    "......WWWW......",
    "......W..W......",
    ".....WW..WW.....",
    ".....W....W.....",
    "....WW....WW....",
    "....W..GG..W....",
    "...WW.GGGG.WW...",
    "...W.GGGGGG.W...",
    "...WWGGGGGGWW...",
    "....WWWWWWWW....",
    "................",
    "................",
], W="#E8E8F0", G="#7CF67C")

ICONS["MONGODB"] = _i([
    ".......G........",
    "......GGG.......",
    ".....GGGGG......",
    ".....GGGGGG.....",
    "....GGGGGGGG....",
    "....GGGGGGGG....",
    "...GGGGGGGGGG...",
    "...GGGGDGGGGG...",
    "...GGGGDGGGGG...",
    "...GGGGDGGGGG...",
    "....GGGDGGGG....",
    ".....GGDGGG.....",
    "......GDGG......",
    ".......D........",
    ".......D........",
    "................",
], G="#4DB33D", D="#1F5C18")

ICONS["FIREBASE"] = _i([
    "................",
    ".......OO.......",
    "......OOOO......",
    ".....OOYYOO.....",
    ".....OOYYOO.....",
    "....OOYYYYOO....",
    "....OYYYYYYO....",
    "...OOYYYYYYOO...",
    "...OYYYYYYYYO...",
    "..OOYYYYYYYYOO..",
    "..OYYYYYYYYYYO..",
    "..OYYYYYYYYYYO..",
    "..OOYYYYYYYYOO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
], O="#F5820D", Y="#FFCA28")

ICONS["DOCKER"] = _i([
    "................",
    "........BB......",
    ".....BB.BB.BB...",
    "..BB.BB.BB.BB...",
    "..BB.BB.BB.BB...",
    "..BBBBBBBBBBB...",
    ".BBBBBBBBBBBBB..",
    "BBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBB.",
    ".BBBBBBBBBBBBB..",
    "..BBBBBBBBBBB...",
    "....BBBBBBB.....",
    "................",
    "................",
    "................",
    "................",
], B="#2496ED")

ICONS["LINUX"] = _i([
    ".....KKKKKK.....",
    "....KKKKKKKK....",
    "....KKWWKKWW....",
    "....KKWKKWWK....",
    ".....KKOOKK.....",
    "....KKOOOOKK....",
    "...KKKWWWWKKK...",
    "..KKKWWWWWWKKK..",
    "..KKWWWWWWWWKK..",
    "..KKWWWWWWWWKK..",
    "..KKWWWWWWWWKK..",
    "...KWWWWWWWWK...",
    "...KWWWWWWWWK...",
    "..OOOWWWWWWOOO..",
    ".OOOO.OOOO.OOOO.",
    "................",
], K="#1A1A1A", W="#F0F0F0", O="#F5A623")

ICONS["GIT"] = _i([
    "................",
    "................",
    "...OOO.....OOO..",
    "..OOOOO...OOOOO.",
    "..OOOOO...OOOOO.",
    "...OOO.....OOO..",
    "....O.......O...",
    "....O......O....",
    "....O.....O.....",
    "....OOOOOO......",
    "....O...........",
    "....O...........",
    "...OOO..........",
    "..OOOOO.........",
    "..OOOOO.........",
    "...OOO..........",
], O="#F05033")

ICONS["POSTMAN"] = _i([
    "................",
    ".....OOOOOO.....",
    "...OOOOOOOOOO...",
    "..OOOOWOOOOOOO..",
    "..OOOWWWOOOOOO..",
    ".OOOOWWWWOOOOOO.",
    ".OOOOOWWOOOOOOO.",
    ".OOOOWWOOOOOOOO.",
    ".OOOWWOOOOOOOOO.",
    ".OOOWOOOOOOOOOO.",
    "..OOOOOOOOOOOO..",
    "..OOOOOOOOOOOO..",
    "...OOOOOOOOOO...",
    ".....OOOOOO.....",
    "................",
    "................",
], O="#FF6C37", W="#FFFFFF")
